name: Compile and Lint
on:
  push:
    branches:
      - "main"
  pull_request:
jobs:
  compileLint:
    name: Compile and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js 16
        uses: actions/setup-node@v3.5.0
        with:
          node-version: 16
          cache: "yarn"
      - name: Install dependencies
        run: yarn
      - name: Compile changed files
        run: |
          git config --global core.quotePath false
          yarn compile ${{ github.event_name }} $GITHUB_BASE_REF
      - name: Check Lint
        run: yarn lint:ci
