name: Syntax Enforcer
on:
  schedule:
    - cron: 0 0 */3 * *
  workflow_dispatch:
jobs:
  qa:
    name: Syntax Enforcer
    runs-on: ubuntu-latest
    if: github.repository_owner == 'PreMiD'
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"
      - name: Install dependencies
        run: yarn
      - name: Start SE
        run: |
          git config --global core.quotePath false
          git config --global core.precomposeunicode true
          yarn se
      - name: Commit any changes
        if: always()
        run: |
          git add .;
          if git diff-index --quiet HEAD --; then
            exit 0;
          else
            hub config --global hub.protocol https;
            hub config --global user.email "${GITHUB_EMAIL}";
            hub config --global user.name "${GITHUB_USER}";
            hub remote set-url origin "https://${GITHUB_TOKEN}:x-oauth-basic@github.com/${GITHUB_REPOSITORY}.git";
            git config --local user.email "${GITHUB_EMAIL}";
            git config --local user.name "${GITHUB_USER}";
            git checkout -b semid/qa/`date +%F-%H-%M`;
            git commit -sam "refactor: run syntax enforcer";
            hub pull-request -b "PreMiD:main" -p -m "refactor: semi-weekly SE" -m "*beep boop* I've prettified and refactored some Presences and sorted all metadata files...";
          fi
        env:
          GITHUB_USER: SeMiD
          GITHUB_EMAIL: semid@premid.app
          GITHUB_TOKEN: ${{ secrets.AUTOMERGE }}
