name: Schema Validation Check
on: pull_request
jobs:
  validate:
    name: Schema Validation Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js 16
        uses: actions/setup-node@v3.5.0
        with:
          node-version: 16
          cache: "yarn"
      - name: Install dependencies
        run: yarn
      - name: Run SV
        run: |
          git config --global core.quotePath false
          yarn sv ${{ github.event_name }}
