name: Schema Validation Check
on: [push, pull_request]
jobs:
  validate:
    name: Schema Validation Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v3.1.1
        with:
          node-version: 16
          cache: "yarn"
      - name: Install dependencies
        run: yarn
      - name: Find Changed Files (direct push)
        if: github.event_name == 'push'
        run: |
          git config core.quotepath off # fixes escape sequence issue
          git diff-tree --no-commit-id --name-only -r ${{ github.sha }} --output file_changes.txt
      - name: Find Changed Files (pull request)
        if: github.event_name == 'pull_request'
        uses: PreMiD/changed-files@v3
        id: changed_files
      - name: Write Changed Files (pull request)
        if: github.event_name == 'pull_request'
        uses: DamianReeves/write-file-action@v1.0
        with:
          path: file_changes.txt
          contents: |
            ${{ steps.changed_files.outputs.files_created }}
            ${{ steps.changed_files.outputs.files_updated }}
      - name: Start SV
        run: yarn sv --colors
